### ISSUE TITLE
移動速度の取得方法

### ISSUE THREAD

**Issue by rkdora** [MyDry/gait_tuner#1]
### A案
たなっちがRead.meにかいたように、
> 1.自分の身近なところで、「歩いて間に合う or 走れば間に合うの瀬戸際」をユーザーの経験則から取得
2.地図に始点・終点をポイントし、残り何分から何分の間なら走るなどを入力してもらう

### B案
ダッシュ時→50m走のタイムを入力。
ジョギング・歩行時→平均速度を初期値に設定し、細かい調整を後からできるようにする。
（学習機能をつけれたら面白いと思った）

---
追加案・修正案・補足案等々待ち

**Comment by tanacchi** [comment]
50m 走のタイムを普段の移動速度に使うのはどうかなと思います。
服装（特に靴）や荷物、距離の影響によって実際の速さはだいぶ遅いものになるのでは

**Comment by tanacchi** [comment]
ただ、最初の設定が意外と面倒なのでデフォルト値を設けるのはアリ

**Comment by rkdora** [comment]
確かに、そーゆー面はあるかも。
ただ、自分が出せるMAX速度という面では議論の余地がまだありそう。
現実面でだせる速度か理想的にはだせる速度か。
ちな、ハイヒールとか荷物によって速度が変化する案は個人的に好き

**Comment by tanacchi** [comment]
結局数値選択になりました(;O;)
