### ISSUE TITLE
APIの検討

### ISSUE THREAD

**Issue by rkdora** [MyDry/gait_tuner#2]
**下記に沿ったAPIの検討を求む（下記の修正案も受付）**

目的地までの距離・時間・経路の取得

時間・経路はなかなかないので、距離÷移動速度＝移動時間と算出もあり。
もし移動時間が取得できるようなら、その移動時間×{例・0.3（ダッシュ時）}。

経路はあるに越したことはないが、最悪なくても成り立つ

**Comment by MasatoshiOsugi** [comment]
公共交通機関API
https://www.nttdocomo.co.jp/service/developer/smart_phone/base_station/transportation_search/
駅すぱあとAPI
https://ekiworld.net/service/sier/webservice/free_provision.html

**Comment by tanacchi** [comment]
~~できれば日本語のリファレンスだけで片付けてしまいたいのと、~~
せっかくだしYahoo様のAPIで作りたいので
現状はYOLPで戦っています。

**Comment by tanacchi** [comment]
Google API ゴリゴリになりましたが完成したので良かったです
