### ISSUE TITLE
参考資料

### ISSUE THREAD

**Issue by tanacchi** [MYDRY/gait_tuner#3]
実際に~~役に立った~~お世話になったページだけリストアップ
一番時間をかけたYOLPによる経路取得に関しては、今回使わないので入れてません

## Google Map
[GoogleMapsAPIを使って各ルートの距離/時間を取得する](http://40balmung.hatenablog.com/entry/2016/12/26/183056)    
[Google Map API javascript](https://www.google-mapi.com/)  
[Creating Google Maps Sample App with AngularJS and Onsen UI](https://medium.com/the-web-tub/creating-google-maps-sample-app-with-angularjs-and-onsen-ui-c1325139781e)  
[Developer Guide](https://developers.google.com/maps/documentation/directions/intro)  
[Directions Service](https://developers.google.com/maps/documentation/javascript/directions?hl=ja)  
[Coordinates](https://developers.google.com/maps/documentation/javascript/reference/coordinates)  
[Place IDs](https://developers.google.com/places/place-id)  

## Yahoo Map (YOLP)
[Yahoo! JavaScriptマップAPI](https://developer.yahoo.co.jp/webapi/map/openlocalplatform/v1/js/)  
[YOLPレファレンス](https://developer.yahoo.co.jp/webapi/map/openlocalplatform/v1/js/reference/)
[Coreクラス](https://developer.yahoo.co.jp/webapi/map/openlocalplatform/v1/js/reference/YCore.html)
[Controlクラス](https://developer.yahoo.co.jp/webapi/map/openlocalplatform/v1/js/reference/YControl.html)  
[Featureクラス](https://developer.yahoo.co.jp/webapi/map/openlocalplatform/v1/js/reference/YFeature.html)  

## Data Base
[データベースの利用方法](https://docs.monaca.io/ja/sampleapp/tips/database/)
[openDatabase (NotesDbDirectory - JavaScript™)](https://www.ibm.com/support/knowledgecenter/ja/SSVRGU_9.0.1/reference/r_domino_DbDirectory_openDatabase.html)  
[SQLコマンド一覧](https://qiita.com/kenju/items/313b5640da05834a53aa#update)  
[Web SQL Database APIによるデータベース・アクセス (2/6)](https://www.tuyano.com/index3?id=221001&page=2)  
[ブラウザのDBにアクセスする](https://qiita.com/hys-rabbit/items/6dfc55f35db24614107d)  

## javascript
[JavaScript リファレンス](https://msdn.microsoft.com/ja-jp/library/yek4tbz0(v=vs.94).aspx)  
[関数 (JavaScript)](https://msdn.microsoft.com/ja-jp/library/yh6c50h7(v=vs.94).aspx)  
[JavaScript のスコープを理解する](http://tacamy.hatenablog.com/entry/2012/12/30/191125)  
[Google流 JavaScript におけるクラス定義の実現方法](http://www.yunabe.jp/docs/javascript_class_in_google.html)
[組み込みオブジェクト (JavaScript)](https://msdn.microsoft.com/ja-jp/library/4zx5dkc9(v=vs.94).aspx)  
[JavaScriptで位置情報を取得する方法](https://syncer.jp/how-to-use-geolocation-api)  
[JavaScript 現在のページをリロードしたい](https://qiita.com/39_isao/items/1c26314d1dae8be539a5)  
[windowオブジェクト](https://qiita.com/tsukishimaao/items/39d22fd9178546d6cdeb)
[innerText の注意点と、textContent のススメ](http://okakacacao.wpblog.jp/technology/innertext-and-textcontent)  
[JSON.parse 関数 (JavaScript)](https://msdn.microsoft.com/ja-jp/library/cc836466(v=vs.94).aspx)  
[外部JavaScriptファイルから別の外部JavaScriptファイルをインクルードする方法](http://d.hatena.ne.jp/oinusama/20100204/p1)  
[<input type="time"> 「時刻入力」](https://web-designer.cman.jp/html_ref/abc_list/input_time/)  
[JavaScriptによるフォームの制御](https://developer.mozilla.org/ja/docs/Web/API/Document/forms)  
[ピュアな JavaScript でフォーム(form)系要素の値を取得, 設定する方法一覧](http://phiary.me/js-form-value-accessor/)  
[Dateオブジェクト](https://www.scollabo.com/banban/java/ref_15.html)  
[【JavaScript】日付処理](https://qiita.com/kazu56/items/cca24cfdca4553269cab)  
[文字列を分割する](https://www.ajaxtower.jp/js/string/index1.html)

**Comment by rkdora** [comment]
googlemap　サンプル
[8-1.zip](https://github.com/MyDry/gait_tuner/files/2304949/8-1.zip)

Google Maps用のディレクティブのセット
https://angular-ui.github.io/angular-google-maps/#!/

**Comment by rkdora** [comment]
http://phpjavascriptroom.com/?t=ajax&p=googlemapsapiv3_directions

**Comment by tanacchi** [comment]
## google map
[Map API Overview](https://developers.google.com/maps/documentation/javascript/tutorial)
[日本語リファレンス的なの１](https://lab.syncer.jp/Web/API/Google_Maps/JavaScript/Map/)
[日本語リファレンス的なの２](https://so-zou.jp/web-app/tech/web-api/google/map/#no5)
[日本語リファレンス的なの３](https://www.google-mapi.com/)
[Google Maps JavaScript API V3 Reference](https://developers.google.com/maps/documentation/javascript/reference/)
[Markers](https://developers.google.com/maps/documentation/javascript/markers#add)
[Marker(Reference)](https://developers.google.com/maps/documentation/javascript/reference/marker?hl=ja#Marker.setPosition)
[LatLng](https://developers.google.com/maps/documentation/javascript/reference/coordinates#LatLng)
[Place ID](https://developers.google.com/places/place-id)
[Place ID Finder](https://developers.google.com/maps/documentation/javascript/examples/places-placeid-finder)
[Google Map APIのレスポンシブ対応（地図の中心を追従させる）](https://teratail.com/questions/87933)
[Directions Service](https://developers.google.com/maps/documentation/javascript/directions#UnitSystems)
[Google Maps APIのDirectionsServiceを使って目的地までのルートを表示してみよう！](https://liginc.co.jp/385061)
[Google マップでルート検索のレンダリングをカスタマイズ](https://maps.multisoup.co.jp/blog/2931/)
[JavaScriptにおける数値⇔文字列の型変換あれこれ](https://lealog.hateblo.jp/entry/2013/02/28/005010)
[Google MAPを使用する際の注意点](https://qiita.com/taguchinbo/items/00f85dc5878c51c152f2)
[アイコン一覧](http://waox.main.jp/news/?page_id=229)
[Google Maps の中心にマーカーを表示する](http://lifelog.main.jp/wordpress/?p=233)
[Custom Popups](https://developers.google.com/maps/documentation/javascript/examples/overlay-popup)
[Controls](https://developers.google.com/maps/documentation/javascript/controls)
[Start Styling your Map](https://developers.google.com/maps/documentation/javascript/styling)
[The Google Directions API（ルート検索）1](http://phpjavascriptroom.com/?t=ajax&p=googlemapsapiv3_directions)
[The Google Directions API（ルート検索）2](http://phpjavascriptroom.com/?t=ajax&p=googlemapsapiv3_directions)
[Controls(Reference)](https://developers.google.com/maps/documentation/javascript/reference/control?hl=ja#PanControlOptions)
[Maps(reference)](https://developers.google.com/maps/documentation/javascript/reference/map?hl=ja#MapOptions.streetViewControl)

## javascript
[クラス継承](https://postd.cc/javascript-inheritance-patterns/)
[Object.entries() を使ってObject -> 配列変換](https://qiita.com/kws9/items/6ce80ae1c0fd28a3a9d7)
[throw](https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Statements/throw)
[javascript でselect box の操作](https://www.pazru.net/js/form/5.html)

## html
[select box](https://developer.mozilla.org/ja/docs/Web/HTML/Element/select)

**Comment by tanacchi** [comment]
wikiに移行した方がいいかなー
とりあえず閉じます
